apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline-pr-main
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[git-clone, kaniko]"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
          - name: SKIP_PUSH
            value: "true"
      - name: build
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        taskRef:
          name: kaniko
        params:
          - name: IMAGE
            value: ghcr.io/pabrahamsson/cf-dyn-dns
          - name: DOCKERFILE
            value: ./Containerfile
          - name: EXTRA_ARGS
            value: ["--no-push"]
          - name: WRITER_IMAGE
            value: registry.access.redhat.com/ubi10/ubi-minimal:10.0-1747219969
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
