apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline-pr-main
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "10"
spec:
  params:
    - name: repo_name
      value: "{{ repo_name }}"
    - name: repo_owner
      value: "{{ repo_owner }}"
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineRef:
    params:
      - name: kind
        value: pipeline
      - name: name
        value: pipeline-pr-build
      - name: namespace
        value: openshift-pipelines
    resolver: cluster
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
